### ISSUE TITLE
When I place the new solution explorer - the tab is still "Solution Explorer"

### ISSUE THREAD

**Issue by noam-honig** [stickleprojects/NamedSolutionExplorer#6]
![image](https://user-images.githubusercontent.com/16635859/39986979-07b4f8fc-576c-11e8-95ba-af065291975b.png)

**Comment by stickleprojects** [comment]
Looks like substantial work on this one - the tab name is controlled by the docker window and i cannot find any mechanism to get at this as were using the "new scoped solution" command rather than creating our own new tool and hosting the solution explorer  - doesnt help that my microsoft login goes into a perpetual cycle so  i cannot read any microsoft docs
